# NumPy
Se centra en el manejo de arrays

In [16]:
import numpy as np

In [17]:
# creo una lista tipica de  python 
lista = [1,2,3,4]
lista

[1, 2, 3, 4]

In [18]:
#llevo mi lista a un array de numpy
arr = np.array(lista)

In [19]:
# matriz en py
matriz = [[1,2,3]
         ,[4,5,6]
         ,[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Indexación

In [20]:
print(arr[1])

2


In [21]:
print(matriz[0][2]) #o matriz[0,2]

3


## Slice

In [22]:
arr[1:4]
arr[::2]

array([1, 3])

## Tipos de datos

In [23]:
arr2 = np.array([1,2,3,4], dtype = "float64") #utilizarlo como float ayuda al rendimiento en redes neuronales
arr2.dtype

dtype('float64')

In [24]:
#para modificar el tipo de datos luego de definido el array uso .astype
arr = arr.astype(np.float64)
arr.dtype

dtype('float64')

## Dimensiones

|           |dimensión  |                                           |
|-----------|-----------|-------------------------------------------|
|scalar     |0          |valor                                      |
|vector     |1          |                                           |
|matrix     |2          |caracteríaticas, ejemplos                  |
|"cubo"     |3          |características, ejemplos, serie de tiempo |
|tensor     |n          |alto, ancho, ejemplos, canales             |

In [25]:
scalar =np.array(42)
vector = np.array([1,2,3])
matriz = np.array([[1,2],[3,4]])
tensor = np.array([matriz, matriz])
#con ndim obtengo las dimensiones
print("scalar: ",str(scalar.ndim),
" vector: ", str(vector.ndim),
" matriz: ", str(matriz.ndim),
" tensor: ", tensor.ndim)

scalar:  0  vector:  1  matriz:  2  tensor:  3


### Agregar o eliminar dimensiones

In [26]:
# Cuando quiero tener un determinado número de dimensiones:
falsoVector = np.array([1,2,3], ndmin=10)
falsoVector.ndim
WfalsoVector

NameError: name 'WfalsoVector' is not defined

In [ ]:
# Para expandir un array a más dimensiones
expand = np.expand_dims(np.array([1,2,3]), axis = 0)
print(expand)
print(expand.ndim)

[[1 2 3]]
2


In [ ]:
# Para eliminar dimensiones que no estoy utilizando
delete = np.squeeze(expand)
print(delete)
print(delete.ndim)

[1 2 3]
1


## Creando arrays desde NumPy

In [ ]:
arr = np.arange(0,10) #analogo a range(0,10) de py puro
# puedo usar arr = np.arange(0,10,2) para usar un paso de 2
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros(3) #crea array de ceros
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,100) #crea una distribución normalizada de 100 datos entre 0 y 10

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.eye(4) #crea una matriz con la diagonal en 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand() #genera valor aleatorio entre  0 y 1
np.random.rand(4) #genera vector con valores aleatorios entre  0 y 1
np.random.rand(4,4) #genera matriz con valores aleatorios entre 0 y 1

array([[6.55104251e-01, 4.41350591e-01, 5.84560818e-05, 3.41835663e-02],
       [5.49171097e-01, 7.12370084e-01, 3.63247457e-01, 1.70920096e-01],
       [8.29042685e-01, 4.57449802e-01, 9.77609846e-02, 7.17768116e-01],
       [1.50096936e-01, 6.66405909e-01, 4.56800547e-01, 2.88780274e-01]])

In [ ]:
np.random.randint(1,15)
np.random.randint(1, 100, (10,10)) #devuelve valores aleatorios de 1 a 100 en una matriz de 10x10

array([[72, 17, 38, 27, 87, 22, 54, 25, 11, 16],
       [ 3, 80, 86, 97, 26, 24, 58, 43, 79, 58],
       [25, 27,  4, 95, 44, 74,  3, 14, 81, 12],
       [84, 36, 85,  8, 13, 35, 74, 43, 79, 63],
       [20, 69, 19, 94, 31, 49,  7, 79, 14, 51],
       [90, 74, 64, 13, 45, 21, 41, 39, 71, 98],
       [93, 88, 52, 58, 93, 53, 66, 72, 48, 85],
       [58, 73, 93, 44, 91, 14, 92, 46, 37, 15],
       [61, 21, 56,  5, 26, 17, 55, 28, 12, 80],
       [29, 99, 43, 97, 66, 40, 77, 73, 74, 32]])

## Shape y Reshape

Shape indica forma que tiene un arreglo

In [ ]:
arr3 = np.random.randint(1,20, (3,3))
arr3

array([[ 5,  6,  3],
       [15, 13,  5],
       [19,  5, 10]])

In [ ]:
arr3.shape

(3, 3)

In [ ]:
arr3.reshape(1,9) #cambia la forma de un array
#otra sintaxis:
#np.reshape(arr3, (1,9))

array([[ 5,  6,  3, 15, 13,  5, 19,  5, 10]])

In [ ]:
arr3.reshape(9,1)

array([[ 5],
       [ 6],
       [ 3],
       [15],
       [13],
       [ 5],
       [19],
       [ 5],
       [10]])

In [ ]:
np.reshape(arr3, (1,9), "C") #paso a un orden usado en C o en F
#para guardarlo en el formato optimizado en mi computadora uso "A"

array([[ 5,  6,  3, 15, 13,  5, 19,  5, 10]])

## Funciones principales

In [27]:
arr4 = np.random.randint(1,20 ,10)
matriz2 = arr4.reshape(2,5)
matriz2

array([[ 2,  7,  4, 15,  1],
       [10,  9, 15,  5,  5]])

In [ ]:
arr4.max()

15

In [ ]:
arr4.min()

1

In [ ]:
matriz2.max(0)

array([ 4, 15, 13, 12, 14])

In [ ]:
matriz2.argmax(0) #devuelve el indice del maximo

array([0, 1, 0, 1, 0], dtype=int64)

In [ ]:
matriz2.ptp()

14

In [ ]:
np.percentile(arr4, 50)

12.0

In [ ]:
arr4.sort()
arr4

array([ 1,  4,  6, 11, 12, 12, 13, 14, 14, 15])

In [ ]:
np.median(arr4)

12.0

In [ ]:
np.std(arr4)

4.5563142999578075

In [ ]:
np.mean(arr4)

10.2

In [ ]:
np.var(arr4)

20.76

In [ ]:
#concatenar arrays
a = np.array([[1,2],[3,4]])
b = np.array([4,6], ndmin=2)

In [ ]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [4, 6]])

In [ ]:
#transpuesta utilizo .T
b = b.T
np.concatenate((a, b), axis=1)

array([[1, 2, 4],
       [3, 4, 6]])

## Comando COPY

Cuando defino un array en funcion de otro anterior cuando modifique al nuevo voy a estar haciendo referencia a elementos de memoria definidos inicialmente. De esta forma corro el riesgo de dañar mis datos originales. Para evitar esto debo copiarlos antes que nada.

In [ ]:
arr_copy = arr.copy()
arr_copy[0]=10
print(arr)
print(arr_copy)

[0 1 2 3 4 5 6 7 8 9]
[10  1  2  3  4  5  6  7  8  9]


## Condiciones

In [ ]:
arr = np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr[(arr>4) & (arr<8)]

array([5, 6, 7], dtype=int8)

## Operaciones

In [31]:
arr4_copy = arr4.copy()
arr4_copy

array([ 2,  7,  4, 15,  1, 10,  9, 15,  5,  5])

In [30]:
arr4_copy*2

array([ 4, 14,  8, 30,  2, 20, 18, 30, 10, 10])

In [32]:
1/arr4_copy

array([0.5       , 0.14285714, 0.25      , 0.06666667, 1.        ,
       0.1       , 0.11111111, 0.06666667, 0.2       , 0.2       ])